# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: citadel-online-research-agent-vnet
metadata:
  template: citadel-online-research-agent-vnet@0.0.1-beta

infra:
  provider: bicep
  path: .

pipeline:
  provider: github

services:
  api:
    project: ./src
    language: python
    host: containerapp
    docker:
      context: ./src
      remoteBuild: true
